language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
env:
  - MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
before_script: mvn javadoc:javadoc
script: mvn -q cobertura:cobertura -PreducedMemory
after_success:
  - bash <(curl -s https://codecov.io/bash)
