name: Update Korpyhe Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Korpyhe Version'
        required: true

jobs:
  update-koryphe-version:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    steps:

      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Set up Github credentials
        run: |
          git config user.name Gaffer
          git config user.email github-actions@github.com

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Update Korpyhe Version
        run: ./cd/updateKorypheVersion.sh ${{ github.event.inputs.version }}
